"""Reproduce a source-bound Nanvix bitmap contract extract; never edit Nanvix."""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from pathlib import Path


HERE = Path(__file__).resolve().parent
INPUTS = HERE / "inputs"
SEALED = INPUTS / "sealed"
MANIFEST = INPUTS / "provenance.json"
SELECTION = HERE / "source-selection.json"
BITMAP = "src/libs/bitmap/src/lib.rs"
BITMAP_SPEC = "src/libs/bitmap/src/lib.spec.rs"
RAW = "src/libs/raw-array/src/lib.rs"
RAW_SPEC = "src/libs/raw-array/src/lib.spec.rs"
ERROR = "src/libs/error/src/lib.rs"
ERRNO = "src/libs/sysapi/src/errno.rs"
FFI = "src/libs/sysapi/src/ffi.rs"
TARGETS = {
    "number_of_bits": (206, 214, 216, False),
    "usage": (227, 235, 237, False),
    "alloc": (249, 273, 280, True),
    "set": (519, 546, 570, True),
}


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def build(source: Path) -> tuple[dict[str, bytes], dict]:
    originals = {
        name: (source / name).read_bytes()
        for name in (BITMAP, BITMAP_SPEC, RAW, RAW_SPEC, ERROR, ERRNO, FFI, "LICENSE.txt")
    }
    expected = json.loads(SELECTION.read_text())["source_hashes"]
    actual = {name: sha256(data) for name, data in originals.items()}
    if actual != expected:
        changed = sorted(name for name in actual if actual[name] != expected.get(name))
        raise ValueError(
            "Source differs from the reviewed, hash-pinned extraction layout: "
            + ", ".join(changed)
            + ". Review source spans before updating source-selection.json."
        )
    chunks: list[bytes] = []
    spans: list[dict] = []

    def added(text: str) -> None:
        chunks.append(text.encode())

    def copied(name: str, first: int, last: int) -> bytes:
        original = originals[name]
        lines = original.splitlines(keepends=True)
        if not 1 <= first <= last <= len(lines):
            raise ValueError(f"Invalid source span: {name}:{first}-{last}")
        start = sum(map(len, lines[:first - 1]))
        data = b"".join(lines[first - 1:last])
        offset = sum(map(len, chunks))
        spans.append({
            "source": name, "source_lines": [first, last],
            "source_bytes": [start, start + len(data)],
            "fixture": "bitmap_contract.rs",
            "fixture_bytes": [offset, offset + len(data)],
            "sha256": sha256(data),
        })
        chunks.append(data)
        return data

    added("// Copyright(c) The Maintainers of Nanvix.\n")
    added("// Licensed under the MIT License; see LICENSE.txt.\n")
    added("// Generated by seal.py. Mutation bodies are explicitly external; contracts are unchanged.\n")
    added("#![allow(dead_code, non_camel_case_types)]\n")
    added("use vstd::prelude::*;\nuse core::ptr;\nmod errno;\nuse errno::*;\nmod ffi {\n")
    copied(FFI, 24, 24)
    added("}\n\n")
    copied(ERROR, 34, 281)
    added("\n")
    copied(ERROR, 693, 697)
    added("\nverus! {\n")
    copied(ERROR, 864, 868)
    added("}\n\n")
    copied(RAW, 61, 67)
    added("\n")
    copied(RAW, 200, 205)
    added("\n")
    copied(RAW, 216, 223)
    added("\nverus! {\n")
    copied(RAW_SPEC, 66, 78)
    added("}\n\n")
    copied(BITMAP, 58, 71)
    added("\n")
    copied(BITMAP_SPEC, 8, 83)
    added("}\n")
    copied(BITMAP_SPEC, 295, 342)
    added("\n")
    copied(BITMAP, 77, 78)
    targets = []
    for name, (first, header_last, body_last, stubbed) in TARGETS.items():
        added("\n")
        if stubbed:
            added("    #[verus_verify(external_body)]\n")
        header = b"".join(originals[BITMAP].splitlines(keepends=True)[first - 1:header_last])
        if f"pub fn {name}(".encode() not in header or not header.rstrip().endswith(b"{"):
            raise ValueError(f"Target source moved: {name}")
        copied(BITMAP, first, header_last if stubbed else body_last)
        if stubbed:
            added("        unimplemented!()\n    }\n")
        targets.append({
            "name": name, "source": BITMAP, "source_lines": [first, body_last],
            "original_header": header.decode(),
            "original_header_sha256": sha256(header),
            "implementation_body_stubbed": stubbed,
            "stub_annotation": "#[verus_verify(external_body)]" if stubbed else None,
        })
    added("}\n")
    outputs = {
        "bitmap_contract.rs": b"".join(chunks),
        "errno.rs": originals[ERRNO],
        "LICENSE.txt": originals["LICENSE.txt"],
    }
    revision = subprocess.check_output(["git", "-C", str(source), "rev-parse", "HEAD"], text=True).strip()
    status = subprocess.check_output(
        ["git", "-C", str(source), "status", "--porcelain", "--", *originals], text=True,
    )
    manifest = {
        "schema_version": 1,
        "classification": "dependency-closed, source-sealed contract extract",
        "source_repository": "https://github.com/nanvix/nanvix",
        "source_checkout": str(source),
        "source_revision": revision,
        "source_worktree_status": status.splitlines(),
        "source_hashes": {name: sha256(data) for name, data in originals.items()},
        "fixture_hashes": {name: sha256(data) for name, data in outputs.items()},
        "copied_spans": spans,
        "whole_file_copies": {"errno.rs": ERRNO, "LICENSE.txt": "LICENSE.txt"},
        "targets": targets,
        "transformations": [
            "Co-locate exact source type declarations and specification dependencies in one crate.",
            "Retain the original RawArrayStorage opaque external type, RawArray uninterpreted View, and invariant.",
            "Retain the complete ErrorCode enum, errno constants, Error fields, and external type specifications.",
            "Retain the supported x86/x86_64 c_int = i32 source alias; add only module/import scaffolding.",
            "Omit unselected executable methods, unrelated proof lemmas, verified tests, and build metadata.",
            "Preserve getter bodies; replace alloc/set bodies with explicitly external unimplemented stubs.",
        ],
        "proof_boundary": (
            "Contract determinism only under the checker observation policy. This is not native Cargo "
            "verification, implementation correctness, allocation liveness, or a specification-quality verdict. "
            "No target requires/ensures clauses, Views, invariants, or type fields are changed."
        ),
    }
    return outputs, manifest


def prepare(source: Path) -> dict:
    source = source.resolve()
    if INPUTS.resolve().is_relative_to(source):
        raise ValueError("Generated inputs must not be written inside the Nanvix source repository")
    outputs, manifest = build(source)
    SEALED.mkdir(parents=True, exist_ok=True)
    for name, data in outputs.items():
        (SEALED / name).write_bytes(data)
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n")
    return check(source)


def check(source: Path | None = None) -> dict:
    manifest = json.loads(MANIFEST.read_text())
    if manifest["source_hashes"] != json.loads(SELECTION.read_text())["source_hashes"]:
        raise ValueError("Local inputs do not match the reviewed source selection")
    for name, expected in manifest["fixture_hashes"].items():
        if sha256((SEALED / name).read_bytes()) != expected:
            raise ValueError(f"Fixture changed: {name}")
    for span in manifest["copied_spans"]:
        data = (SEALED / span["fixture"]).read_bytes()
        first, last = span["fixture_bytes"]
        if sha256(data[first:last]) != span["sha256"]:
            raise ValueError(f"Copied span changed: {span}")
    if source is not None:
        for name, expected in manifest["source_hashes"].items():
            if sha256((source / name).read_bytes()) != expected:
                raise ValueError(f"Original source changed: {name}")
        outputs, rebuilt = build(source)
        for name, data in outputs.items():
            if (SEALED / name).read_bytes() != data:
                raise ValueError(f"Extract does not reproduce: {name}")
        if rebuilt["copied_spans"] != manifest["copied_spans"]:
            raise ValueError("Source span provenance changed")
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path)
    parser.add_argument("--write", action="store_true", help="Explicitly regenerate the extract and seal")
    args = parser.parse_args()
    if args.write:
        if args.source_root is None:
            parser.error("--write requires --source-root")
        prepare(args.source_root.resolve())
    check(args.source_root.resolve() if args.source_root else None)
    print("Verified sealed Nanvix bitmap source spans and fixture hashes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
